import React from 'react';

export const themes = {
  light: {
    key: 'light',
    primary: '#83B240',
    primaryVariant: '#5b8a2d',
    secondary: '#1063A9',
    secondaryVariant: '#00488A',
    tertiary: '#83B240',
    tertiaryVariant: '#3A681C',
    background: '#ECF0F1',
    snackbar: '#000000dd',
    surfacePrimary: '#FFFFFF',
    surfaceSecondary: '#E8F5E9',
    surfaceTertiary: '#E1F5FE',
    error: '#B00020',
    success: '#4BB543',
    warning: '#FFD24D',
    meta: '#9E9E9E',
    disabled: '#E0E0E0',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onBackground: '#121212',
    onSurfacePrimary: '#121212',
    onSurfaceSecondary: '#333',
    onSurfaceTertiary: '#333',
    onError: '#FFFFFF',
    onSuccess: '#FFFFFF',
    onWarning: '#121212',
    onDisabled: '#8B8B8B',
  },
  dark: {
    key: 'dark',
    primary: '#93deac',
    primaryVariant: '#29c770',
    secondary: '#91C8Eb',
    secondaryVariant: '#2D93D9',
    background: '#333',
    snackbar: '#121212',
    surfacePrimary: '#121212',
    surfaceSecondary: '#706c61',
    surfaceTertiary: '#202124',
    error: '#CF6679',
    success: '#A6D9A3',
    warning: '#FFDE81',
    meta: '#F1F3F4',
    disabled: '#3C3C3C',
    onPrimary: '#333',
    onSecondary: '#FFFFFF',
    onBackground: '#FFFFFF',
    onSurfacePrimary: '#FFFFFF',
    onSurfaceSecondary: '#FFFFFF',
    onSurfaceTertiary: '#FFFFFF',
    onError: '#333',
    onSuccess: '#333',
    onWarning: '#333',
    onDisabled: '#9E9E9E',
  },
};

export const ThemeContext = React.createContext({
  theme: themes.dark,
  toggleTheme: () => {},
});
