import React from 'react';

export const themes = {
  light: {
    key: 'light',
    primary: '#e60014',
    primaryVariant: '#E50A17',
    secondary: '#E50A17',
    secondaryVariant: '#E50A17',
    tertiary: '#131315',
    tertiaryVariant: '#131315',
    background: '#FFFFFF',
    snackbar: '#000000dd',
    surfacePrimary: '#F4F4F4',
    surfaceSecondary: '#F4F4F4',
    surfaceTertiary: '#E2E2E2',
    error: '#B00020',
    success: '#4BB543',
    warning: '#FFD24D',
    meta: '#9E9E9E',
    disabled: '#E0E0E0',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onBackground: '#404040',
    onSurfacePrimary: '#404040',
    onSurfaceSecondary: '#707070',
    onSurfaceTertiary: '#FFFFFF',
    onError: '#FFFFFF',
    onSuccess: '#FFFFFF',
    onWarning: '#121212',
    onDisabled: '#8B8B8B',
  },
  dark: {
    key: 'dark',
    primary: '#93deac',
    primaryVariant: '#29c770',
    secondary: '#91C8Eb',
    secondaryVariant: '#2D93D9',
    background: '#333',
    snackbar: '#121212',
    surfacePrimary: '#121212',
    surfaceSecondary: '#706c61',
    surfaceTertiary: '#202124',
    error: '#CF6679',
    success: '#A6D9A3',
    warning: '#FFDE81',
    meta: '#F1F3F4',
    disabled: '#3C3C3C',
    onPrimary: '#333',
    onSecondary: '#FFFFFF',
    onBackground: '#FFFFFF',
    onSurfacePrimary: '#FFFFFF',
    onSurfaceSecondary: '#FFFFFF',
    onSurfaceTertiary: '#FFFFFF',
    onError: '#333',
    onSuccess: '#333',
    onWarning: '#333',
    onDisabled: '#9E9E9E',
  },
};

export const ThemeContext = React.createContext({
  theme: themes.dark,
  toggleTheme: () => {},
});
